---
- name: Enable cgroup via boot commandline if not already enabled for Ubuntu on a Raspberry Pi
  ansible.builtin.lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: true
    regexp: ^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$
    line: \1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory
  notify: reboot

- name: Install linux-modules-extra-raspi
  ansible.builtin.apt:
    name: linux-modules-extra-raspi
    state: present
  when: ansible_distribution_version is version('24.04', '<')
