---
- name: Reboot k3s_cluster
  hosts: k3s_cluster
  gather_facts: true
  tasks:
    - name: Reboot the nodes (and Wait upto 5 mins max)
      become: true
      ansible.builtin.reboot:
        reboot_command: "{{ custom_reboot_command | default(omit) }}"
        reboot_timeout: 300
