---
argument_specs:
  main:
    short_description: Setup k3s agents
    options:
      apiserver_endpoint:
        description: Virtual ip-address configured on each master
        required: true

      extra_agent_args:
        description: Extra arguments for agents nodes

      group_name_master:
        description: Name of the master group
        default: master

      k3s_token:
        description: Token used to communicate between masters

      proxy_env:
        type: dict
        description: Internet proxy configurations
        default: ~
        options:
          HTTP_PROXY:
            required: true
          HTTPS_PROXY:
            required: true
          NO_PROXY:
            required: true

      systemd_dir:
        description: Path to systemd services
        default: /etc/systemd/system
