# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    # General configuration
    config.vm.box = "generic/ubuntu2204"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.ssh.insert_key = false

    # We currently can not use public-key based authentication on Ubuntu 22.04,
    # see: https://github.com/chef/bento/issues/1405
    config.ssh.username = "vagrant"
    config.ssh.password = "vagrant"

    config.vm.provider :virtualbox do |v|
        v.memory = 2048
        v.cpus = 2
        v.linked_clone = true
    end

    # Control Node 1
    config.vm.define "control1" do |control1|
        control1.vm.hostname = "control1"
        control1.vm.network "private_network", ip: "192.168.30.38"
    end

    # Control Node 2
    config.vm.define "control2" do |control2|
        control2.vm.hostname = "control2"
        control2.vm.network "private_network", ip: "192.168.30.39"
    end

    # Control Node 3
    config.vm.define "control3" do |control3|
        control3.vm.hostname = "control3"
        control3.vm.network "private_network", ip: "192.168.30.40"
    end

    # Worker Node 1
    config.vm.define "node1" do |node1|
        node1.vm.hostname = "node1"
        node1.vm.network "private_network", ip: "192.168.30.41"
    end

    # Worker Node 2
    config.vm.define "node2" do |node2|
        node2.vm.hostname = "node2"
        node2.vm.network "private_network", ip: "192.168.30.42"
    end

    config.vm.provision "ansible",type: "ansible", run: "never" do |ansible|
        ansible.playbook = "../site.yml"
        ansible.inventory_path = "../inventory/sample/hosts.ini"
        ansible.limit = "all"
        ansible.extra_vars = {
            ansible_user: "vagrant",

            # See: https://github.com/flannel-io/flannel/blob/67d603aaf45ef80f5dd39f43714fc5e6f8a637eb/Documentation/troubleshooting.md#Vagrant
            flannel_iface: "eth1",

            # Reduce flakyness in CI with bigger timeouts
            "retry_count" => "60",
        }
    end
end
