---
- name: Apply overrides
  ansible.builtin.import_playbook: >-
    {{ lookup("ansible.builtin.env", "MOLECULE_SCENARIO_DIRECTORY") }}/overrides.yml

- name: Converge
  ansible.builtin.import_playbook: ../../site.yml
