---
- name: configure rc.local for proxmox lxc containers
  become: true
  blockinfile:
    path: /etc/rc.local
    content: "{{ lookup('template', 'templates/rc.local.j2') }}"
    create: true
    state: present
    mode: "u=rwx,g=rx,o=rx"
  notify: reboot server
