---
dependency:
  name: galaxy
driver:
  name: vagrant
.platform_presets:
  - &control
    memory: 2048
    cpus: 2
    groups:
      - k3s_cluster
      - master
  - &node
    memory: 2048
    cpus: 2
    groups:
      - k3s_cluster
      - node
  - &ubuntu
    box: generic/ubuntu2204
    config_options:
      # We currently can not use public-key based authentication on Ubuntu 22.04,
      # see: https://github.com/chef/bento/issues/1405
      ssh.username: "vagrant"
      ssh.password: "vagrant"
platforms:
  - <<: [*control, *ubuntu]
    name: control1
    interfaces:
      - network_name: private_network
        ip: fdad:bad:ba55::de:11
  - <<: [*node, *ubuntu]
    name: node1
    interfaces:
      - network_name: private_network
        ip: fdad:bad:ba55::de:21
provisioner:
  name: ansible
  playbooks:
    converge: ../resources/converge.yml
    side_effect: ../resources/reset.yml
    verify: ../resources/verify.yml
  inventory:
    links:
      group_vars: ../../inventory/sample/group_vars
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # idempotence is not possible with the playbook in its current form.
    - verify
    # We are repurposing side_effect here to test the reset playbook.
    # This is why we do not run it before verify (which tests the cluster),
    # but after the verify step.
    - side_effect
    - cleanup
    - destroy
