---
- name: Apply overrides
  hosts: all
  tasks:
    - name: Override host variables
      ansible.builtin.set_fact:
        # See:
        # https://github.com/flannel-io/flannel/blob/67d603aaf45ef80f5dd39f43714fc5e6f8a637eb/Documentation/troubleshooting.md#Vagrant
        calico_iface: eth1

        # The test VMs might be a bit slow, so we give them more time to join the cluster:
        retry_count: 45

        # Make sure that our IP ranges do not collide with those of the other scenarios
        apiserver_endpoint: 192.168.30.224
        metal_lb_ip_range: 192.168.30.100-192.168.30.109
