---
- name: Deploy calico
  include_tasks: calico.yml
  tags: calico
  when: calico_iface is defined

- name: Deploy metallb pool
  include_tasks: metallb.yml
  tags:
    - service_lb
  when: service_lb_type == "metallb"
