---
- name: Deploy calico
  include_tasks: calico.yml
  tags: calico
  when: use_calico == true

- name: Deploy metallb pool
  include_tasks: metallb.yml
  tags: metallb

- name: Remove tmp directory used for manifests
  file:
    path: /tmp/k3s
    state: absent
