---
- name: Deploy calico
  include_tasks: calico.yml
  tags: calico
  when: calico_iface is defined

- name: Deploy metallb pool
  include_tasks: metallb.yml
  tags: metallb
  when: service_lb_type | default('metallb') == 'metallb'

- name: Remove tmp directory used for manifests
  file:
    path: /tmp/k3s
    state: absent
