---
name: Ansible Check
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-playbook:
    name: playbook
    runs-on: ubuntu-latest

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip3 install yamllint ansible

      - name: Create playbook
        run: cp -R inventory/sample inventory/my-cluster

      - name: run ansible check
        run: ansible-playbook ./site.yml -i ./inventory/my-cluster/hosts.ini --check
