---
name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  cache:
    uses: ./.github/workflows/cache.yml
    needs: [lint]
  test:
    uses: ./.github/workflows/test.yml
    needs: [lint, cache]
