---
name: "CI"
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - '**/.gitignore'
      - '**/FUNDING.yml'
      - '**/host.ini'
      - '**/*.md'
      - '**/.editorconfig'
      - '**/ansible.example.cfg'
      - '**/deploy.sh'
      - '**/LICENSE'
      - '**/reboot.sh'
      - '**/reset.sh'
jobs:
  pre:
    uses: ./.github/workflows/cache.yml
  lint:
    uses: ./.github/workflows/lint.yml
    needs: [pre]
  test:
    uses: ./.github/workflows/test.yml
    needs: [pre, lint]
