---
name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
jobs:
  pre-commit-ci:
    uses: ./.github/workflows/lint.yml
  ensure-pinned-actions:
    uses: ./.github/workflows/lint.yml
  test:
    uses: ./.github/workflows/test.yml
    needs: [pre-commit-ci, ensure-pinned-actions]
