---
name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
jobs:
  pre:
    uses: ./.github/workflows/cache.yml
  lint:
    uses: ./.github/workflows/lint.yml
    needs: [pre]
  test:
    uses: ./.github/workflows/test.yml
    needs: [pre, lint]
