name: Sync Fork

on:
  schedule:
    - cron: '0 20 */1 * *' # run every day at 20:00
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: techno-tim
          base: master
          head: master
